import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import Header from "./(main)/component/header";
import Footer from "./(main)/component/footer";
=======
import Header from "./component/header";
import Footer from "./component/footer";
>>>>>>> 11f83616a67170c7497156c06ba4bfb4166668e4

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        {children}
=======
        <Header />
        {children}
        <Footer />
>>>>>>> 11f83616a67170c7497156c06ba4bfb4166668e4
      </body>
    </html>
  );
}
